# Generated by Django 3.2.12 on 2022-03-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authApp.userprofile')),
                ('stud_id', models.CharField(max_length=200)),
            ],
            bases=('authApp.userprofile',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authApp.userprofile')),
                ('subject', models.CharField(max_length=200)),
            ],
            bases=('authApp.userprofile',),
        ),
    ]
